# Generated by Django 3.0.2 on 2020-02-28 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DetectedThreat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('risk', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=20)),
                ('threat_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Threat')),
            ],
        ),
    ]
