# Generated by Django 3.0.2 on 2020-06-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_origen', models.CharField(max_length=30, null=True)),
                ('ip_destino', models.CharField(max_length=30, null=True)),
                ('puerto_origen', models.CharField(max_length=10, null=True)),
                ('puerto_destino', models.CharField(max_length=30, null=True)),
                ('mensaje', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DetectedThreat',
        ),
        migrations.DeleteModel(
            name='Threat',
        ),
    ]
