# Generated by Django 3.0.2 on 2020-06-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200607_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='correo_enviado',
            field=models.CharField(choices=[('t', 't'), ('f', 'f')], default='f', max_length=3),
        ),
    ]
